version: '3'

services:
  ishtixondb:
    container_name: ishtixondb
    image: postgres
    environment:
      POSTGRES_DB: db_ishtixon
      POSTGRES_USER: ishtixonuser
      POSTGRES_PASSWORD: ishtixonpass
    volumes:
      - postgres_data:/var/lib/postgresql/dataishtixon/
    ports:
      - "5432:5432"
  ishtixonweb:
    container_name: ishtixon
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - ishtixondb
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
