version: '3'

services:
  forishdb:
    container_name: forishdb
    image: postgres
    environment:
      POSTGRES_DB: db_forish
      POSTGRES_USER: forishuser
      POSTGRES_PASSWORD: forishpass
    volumes:
      - postgres_data:/var/lib/postgresql/dataforish/
    ports:
      - "5432:5432"
  forishweb:
    container_name: forish
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - forishdb
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
